### ISSUE TITLE
calendar model

### ISSUE THREAD

**Issue by alexandra-strojny** [nero-strojny/cookbook-backend#90]
Add a new model to save a user/household's weekly calendar to the database

calendar: {
calendarId: <String>
startDate: <Date> //Implicitly sundays
owner: <householdId>
monday: <recipeId>
tuesday: <recipeId>
wednesday: <recipeId>
thursday: <recipeId>
friday: <recipeId>
saturday: <recipeId>
sunday: <recipeId>
}

**Comment by alexandra-nero** [comment]
We also need to update the householdDB file to store these calendars.
